### ISSUE TITLE
The timeout for get requests is placed in params

### ISSUE THREAD

**Issue by GeraldWhitehead** [geventhttpclient/geventhttpclient#223]
I'm using locust's FastHttpUser for stress testing, and after I set the timeout timeout, if it's a get request, it's added to the params. I checked your documentation and found that there is no timeout parameter, so I changed the parameter to network_timeout, and when I run the test, it is also added to the params, as follows
![image](https://github.com/geventhttpclient/geventhttpclient/assets/167045125/c696b5fe-550a-40d3-8972-e040241f02c2)
I checked the source code and found that kw is assigned to params when params is None, I don't understand why it is set this way, how should I set the timeout correctly?
![image](https://github.com/geventhttpclient/geventhttpclient/assets/167045125/22b22948-e415-4cca-8467-f33a90418817)
The version I am using is 2.3.1

**Comment by ml31415** [comment]
The timeout should be set on a per-session basis, not a per-request one.

**Comment by GeraldWhitehead** [comment]
> Maybe we should have a "timeout" keyword argument, and just raise an according error if it's set, to avoid confusion?

If the timeout is set in a single request, the single request timeout prevails. Instead of throwing an error, sometimes the user may have to set it based on the individual request, after all, the response time of each interface is faster or slower. If you set it in the session, consider overriding the timeout in the request.

**Comment by ml31415** [comment]
> consider overriding the timeout in the request.

And that's exactly the issue. The timeout is set on the sockets, and the sockets are shared within a session, pooled and reused. So the only reasonable place to set a timeout is for the session. If you want to have clients with different timeout behavior, you should set this on a session and use these sessions accordingly. The only way to "override" this, would be to create a different session "under the hood" and this would clearly do more harm than good.

But it's clear that this should throw an error, instead of sending out unintended parameters.

**Comment by ml31415** [comment]
@cyberw This seems to be purely a locust issue. I just checked, the requests compat module already raises an issue when using timeout as a keyword argument. `UserAgent.urlopen` doesn't, but never did, so it is just considered as an ordinary keyword argument leading to the described issue. If in doubt, I suggest you catch the `timeout=` keyword there.

**Comment by cyberw** [comment]
We're switching to request compat mode some time, I just havent gotten around to it yet..
